# 教程链接
https://www.numpy.org.cn/user_guide/quickstart_tutorial/the_basics.html

In [1]:
import numpy as np

In [2]:
# demo
a = np.array([2,3,4])
print(a)

[2 3 4]


In [3]:
# 元素类型
a.dtype

dtype('int64')

In [4]:
b = np.array([1.2,3.5,5.1])

In [5]:
b

array([1.2, 3.5, 5.1])

In [6]:
a = np.array(1,2) #错误示例

TypeError: data type not understood

In [7]:
a = np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
b = np.array([(1.5,2,3),(4,5,6)])

In [10]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array([[1,2],[3,4]],dtype=complex )

In [12]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
# zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
# empty
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
# ones
np.ones((2,3,4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [17]:
# empty
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
# np arange
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [19]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
# pi
from numpy import pi
pi

3.141592653589793

In [21]:
# linspace
print(np.arange(10,30,5))
print(np.linspace(10,30,5))

[10 15 20 25]
[10. 15. 20. 25. 30.]


In [22]:
a = np.arange(6)

In [23]:
a

array([0, 1, 2, 3, 4, 5])

In [24]:
b = np.arange(12).reshape(4,3)

In [25]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
a = np.array([20,30,40,50])

In [27]:
b = np.arange(4)

In [28]:
b 

array([0, 1, 2, 3])

In [29]:
c = a - b

In [30]:
c

array([20, 29, 38, 47])

In [31]:
b ** 2

array([0, 1, 4, 9])

In [32]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [33]:
a < 30

array([ True, False, False, False])

In [34]:
a

array([20, 30, 40, 50])

In [35]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [36]:
A

array([[1, 1],
       [0, 1]])

In [37]:
B

array([[2, 0],
       [3, 4]])

In [38]:
A * B

array([[2, 0],
       [0, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [41]:
A.T

array([[1, 0],
       [1, 1]])

In [42]:
a = np.ones((2,3), dtype=int)

In [43]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
a *= 3

In [45]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
A,B

(array([[1, 1],
        [0, 1]]), array([[2, 0],
        [3, 4]]))

In [47]:
A

array([[1, 1],
       [0, 1]])

In [48]:
b

array([0, 1, 2, 3])

In [49]:
B

array([[2, 0],
       [3, 4]])

In [50]:
a = np.ones((2,3),dtype=int)
b = np.random.random((2,3))

In [51]:
a *= 3

In [52]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
b += a

In [54]:
b

array([[3.57751758, 3.16035012, 3.27565276],
       [3.92450069, 3.02907245, 3.24224015]])

In [55]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [56]:
s = np.ones(3,dtype=np.int32)

In [57]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [58]:
b = np.linspace(0,pi,3)

In [59]:
b.dtype.name

'float64'

In [60]:
c = a + b

In [61]:
c

array([[3.        , 4.57079633, 6.14159265],
       [3.        , 4.57079633, 6.14159265]])

In [62]:
c.dtype

dtype('float64')

In [63]:
d = np.exp(c*1j)

In [64]:
d

array([[-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j],
       [-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j]])

In [65]:
d.dtype.name

'complex128'

In [66]:
np.exp?

In [67]:
a = np.random.random((2,3))

In [71]:
a

array([[0.91774819, 0.08635176, 0.01686013],
       [0.86472091, 0.26764879, 0.13322891]])

In [72]:
a.sum()

2.2865586965654074

In [73]:
a.min()

0.016860133948334965

In [74]:
a.max()

0.9177481944123914

In [75]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [77]:
b.min(axis=1)

array([0, 4, 8])

In [78]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [79]:
b.cumsum?

In [80]:
b = np.arange(3)

In [81]:
b

array([0, 1, 2])

In [82]:
np.exp(B)

array([[ 7.3890561 ,  1.        ],
       [20.08553692, 54.59815003]])

In [83]:
np.sqrt(B)

array([[1.41421356, 0.        ],
       [1.73205081, 2.        ]])

In [84]:
B = np.arange(3)
C = np.array([2.,-1,4])

In [85]:
C

array([ 2., -1.,  4.])

In [86]:
B

array([0, 1, 2])

In [87]:
np.add(B,C)

array([2., 0., 6.])

In [88]:
a = np.arange(10) ** 3

In [89]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [90]:
a[2]

8

In [91]:
a[2:5]

array([ 8, 27, 64])

In [92]:
a[: :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [93]:
for i in a:
    print(i**(1/3.0))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [94]:
def f(x,y):
    return 10 * x + y

In [95]:
b = np.fromfunction(f,(5,4), dtype=int)

In [96]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [97]:
b[-1]

array([40, 41, 42, 43])

In [98]:
b[0]

array([0, 1, 2, 3])

In [99]:
b[:, 0]

array([ 0, 10, 20, 30, 40])

In [100]:
b[:,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [101]:
b.shape

(5, 4)

In [102]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [103]:
for e in b.flat:
    print(e)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
