## Ndarray
N 维数组对象 

## ndarray 内部组成
一个指向数据（内存或内存映射文件中的一块数据）的指针。

数据类型或 dtype，描述在数组中的固定大小值的格子。

一个表示数组形状（shape）的元组，表示各维度大小的元组。

一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。

In [2]:
# demo
import numpy as np
a = np.array([4,5,6])
print(a)

[4 5 6]


In [5]:
# demo
a = np.array([[2,4],[6,8]])
print(a)

[[2 4]
 [6 8]]


In [7]:
a = np.array([1,2,3,4,5], ndmin =  2)  
print(a)

[[1 2 3 4 5]]
