In [1]:
import numpy.matlib 
import numpy as np
 
print (np.matlib.empty((2,2)))
# 填充为随机数据

[[ 1.49166815e-154 -4.33266758e-311]
 [ 1.48219694e-323  0.00000000e+000]]


In [2]:
import numpy.matlib 
import numpy as np 
 
print (np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [3]:
import numpy.matlib 
import numpy as np 
 
print (np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]
